version: '3.7'
services:
  web:
    container_name: web
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./builddir/:/var/www/html
      - ./docker/conf/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: ./docker
    volumes:
      - ./builddir/:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webapp
      MYSQL_USER: webapp
      MYSQL_PASSWORD: root
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: webapp
      MYSQL_PASSWORD: root
